"""
Student information for this assignment:

On my/our honor, Zhehan Zhang and Kaijie Zhou, this 
programming assignment is my own work and I have not provided this code to 
any other student.

I have read and understand the course syllabus's guidelines regarding Academic
Integrity. I understand that if I violate the Academic Integrity policy (e.g.
copy code from someone else, have the code generated by an LLM, or give my
code to someone else), the case shall be submitted to the Office of the Dean of
Students. Academic penalties up to and including an F in the course are likely.

UT EID 1: ZZ8645
UT EID 2: KZ5233
"""


def length_of_longest_substring_n3(s):
    """
    Finds the length of the longest substring without repeating characters
    using a brute force approach (O(N^3)).

    pre: s is a string of arbitrary length, possibly empty.
    post: Returns an integer >= 0 representing the length of the longest substring
          in s that contains no repeating characters.
    """
    longest_length = 0
    list_length = len(s)
    for i in range(list_length):
        for j in range(i, list_length):
            used_char = {}
            current_substring = s[i:j+1]
            unique_check = True

            for char in current_substring:
                if char in used_char:
                    unique_check = False
                else:
                    used_char[char] = "Exist"

            if unique_check:
                longest_length = max(longest_length, len(current_substring))

    return longest_length


def length_of_longest_substring_n2(s):
    """
    Finds the length of the longest substring without repeating characters
    using a frequency list approach (O(N^2)), converting each character to
    their corresponding numeric representation in ASCII as the index into the
    frequency list.

    pre: s is a string of arbitrary length, possibly empty.
    post: Returns an integer >= 0 representing the length of the longest substring
          in s that contains no repeating characters.
    """
    longest_length = 0
    list_length = len(s)
    ascii_max = 256
    for i in range(list_length):
        char_list = [0] * ascii_max
        unique_check = True
        for j in range(i, list_length):
            char_index = ord(s[j])
            char_list[char_index] += 1

            if char_list[char_index] > 1:
                unique_check = False

            if unique_check:
                longest_length = max(longest_length, j - i + 1)

    return longest_length


def length_of_longest_substring_n(s):
    """
    Finds the length of the longest substring without repeating characters
    using a frequency list approach (O(N)), converting each character to
    their corresponding numeric representation in ASCII as the index into the
    frequency list. However, this approach stops early, breaking out of the inner
    loop when a repeating character is found. You may also choose to challenge
    yourself by implementing a sliding window approach.

    pre: s is a string of arbitrary length, possibly empty.
    post: Returns an integer >= 0 representing the length of the longest substring
          in s that contains no repeating characters.
    """
    longest_length = 0
    start = 0
    char_set= set()

    for i , char in enumerate(s):
        while char in char_set:
            char_set.remove(s[start])
            start += 1
        char_set.add(s[i])
        longest_length = max(longest_length, i - start + 1)

    return longest_length
